import { Metadata } from 'next';

import Info from '@/components/dtc/Info';

import styles from './page.module.css';

export const metadata: Metadata = {
  title: 'More about DTCs | oktaaniDTC',
  description:
    'Diagnostic Trouble Codes (DTCs) are numerical codes generated by the onboard computer systems in modern vehicles to indicate specific issues or problems with various components of the vehicle.',
};

export default function Page() {
  return (
    <>
      <h1>More about DTCs</h1>
      <Info className={styles.container} />
    </>
  );
}
