export default function Info() {
  return (
    <>
      <p className="more-dtc">
        Diagnostic Trouble Codes (DTCs) are numerical codes generated by the
        onboard computer systems in modern vehicles to indicate specific issues
        or problems with various components of the vehicle. These codes are part
        of the On-Board Diagnostics (OBD) system, which is designed to help
        mechanics and technicians quickly identify and diagnose problems with a
        vehicle.
      </p>
      <p className="more-dtc">
        DTCs help streamline the troubleshooting and repair process, making it
        easier to pinpoint and fix problems with a vehicle&apos;s various
        systems. They are standardized across the automotive industry, so a code
        for a specific issue on one car should have the same meaning on another,
        regardless of the make or model.
      </p>
    </>
  );
}
